# Numpy: Numeric computing library
NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

NumPy major contributions are:

Efficient numeric computation with C primitives
Efficient collections with vectorized operations
An integrated and natural Linear Algebra API
A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.
Let's develop on efficiency. In Python, everything is an object, which means that even simple ints are also objects, with all the required machinery to make object work. We call them "Boxed Ints". In contrast, NumPy uses primitive numeric types (floats, ints) which makes storing and computation efficient.

In [1]:
import sys
import numpy as np

In [2]:
# Basic Numpy Arrays 

In [3]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1, 2, 3, 4])

In [5]:
b = np.array([0, .5, 1, 1.5, 2])

In [6]:
a[0], a[1]

(1, 2)

In [7]:

a[0:]

array([1, 2, 3, 4])

In [8]:
a[1:3]

array([2, 3])

In [9]:
a[1:-1]

array([2, 3])

In [10]:
a[::2]

array([1, 3])

In [11]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [12]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [13]:

b[[0, 2, -1]]

array([0., 1., 2.])

# Array Types

In [14]:
a

array([1, 2, 3, 4])

In [15]:
a.dtype


dtype('int32')

In [16]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [17]:
b.dtype


dtype('float64')

In [18]:
np.array([1, 2, 3, 4], dtype=np.float)

C:\Users\Pegah\AppData\Local\Temp/ipykernel_10980/217965920.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1, 2, 3, 4], dtype=np.float)


array([1., 2., 3., 4.])

In [19]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [20]:
c = np.array(['a', 'b', 'c'])

# Dimensions and shapes

In [23]:

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [24]:
A.shape


(2, 3)

In [25]:
A.ndim


2

In [26]:
A.size

6

In [27]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [28]:
B.shape

(2, 2, 3)

In [29]:
B.ndim


3

In [30]:
B.size


12

# Indexing and Slicing of Matrices¶


In [31]:

# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [32]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:

A[1]

array([4, 5, 6])

In [34]:
A[1][0]

4

In [35]:
A[1, 0]

4

In [36]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [38]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [39]:
A[:2, 2:]

array([[3],
       [6]])

In [40]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
A[1] = np.array([10, 10, 10])

In [42]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [43]:
A[2] = 99

In [44]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

# Summary statistics

In [45]:

a = np.array([1, 2, 3, 4])

In [46]:

a.sum()

10

In [47]:
a.mean()

2.5

In [48]:
a.std()

1.118033988749895

In [49]:
a.var()

1.25

In [50]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [51]:
A.sum()

45

In [52]:
A.mean()

5.0

In [53]:
A.std()

2.581988897471611

In [54]:

A.sum(axis=0)

array([12, 15, 18])

In [55]:
A.sum(axis=1)

array([ 6, 15, 24])

In [56]:
A.mean(axis=0)

array([4., 5., 6.])

In [57]:
A.mean(axis=1)

array([2., 5., 8.])

In [58]:

A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [59]:

A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

# Broadcasting and Vectorized operations

In [60]:

a = np.arange(4)

In [61]:
a

array([0, 1, 2, 3])

In [62]:
a + 10

array([10, 11, 12, 13])

In [63]:
a * 10

array([ 0, 10, 20, 30])

In [64]:
a

array([0, 1, 2, 3])

In [65]:

a += 100

In [66]:
a

array([100, 101, 102, 103])

In [67]:

l = [0, 1, 2, 3]

In [68]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [69]:
a = np.arange(4)

In [70]:
a

array([0, 1, 2, 3])

In [71]:
b = np.array([10, 10, 10, 10])

In [72]:
b

array([10, 10, 10, 10])

In [73]:

a + b

array([10, 11, 12, 13])

In [74]:

a * b

array([ 0, 10, 20, 30])

# Boolean arrays
(Also called masks)

In [75]:

a = np.arange(4)

In [76]:
a

array([0, 1, 2, 3])

In [77]:
a[0], a[-1]

(0, 3)

In [80]:
a[[0, -1]]

array([0, 3])

In [81]:
a[[True, False, False, True]]

array([0, 3])

In [82]:
a

array([0, 1, 2, 3])

In [83]:
a >= 2

array([False, False,  True,  True])

In [84]:
a[a >= 2]

array([2, 3])

In [85]:
a.mean()

1.5

In [86]:
a[a > a.mean()]

array([2, 3])

In [87]:
a[~(a > a.mean())]

array([0, 1])

In [88]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [89]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [90]:
A = np.random.randint(100, size=(3, 3))

In [91]:
A

array([[ 1, 83, 96],
       [81, 33, 36],
       [ 6, 51, 44]])

In [92]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([ 1, 96, 33,  6, 44])

In [93]:

A > 30

array([[False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True]])

In [94]:
A[A > 30]

array([83, 96, 81, 33, 36, 51, 44])

# Linear Algebra

In [96]:

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [97]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [98]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [99]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [100]:

B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [101]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

# And performance is also important

In [103]:
l = list(range(100000))

In [104]:
a = np.arange(100000)

In [105]:
%time np.sum(a ** 2)

Wall time: 997 µs


216474736

In [106]:
%time sum([x ** 2 for x in l])

Wall time: 45 ms


333328333350000

#  Useful Numpy functions

In [108]:
# random


In [109]:
np.random.random(size=2)

array([0.59835097, 0.71065766])

In [110]:

np.random.normal(size=2)

array([-0.45543105,  0.71722845])

In [111]:
np.random.rand(2, 4)

array([[0.7021946 , 0.07423462, 0.18014005, 0.4701924 ],
       [0.09725823, 0.4499225 , 0.46376421, 0.56943025]])

In [112]:
# arange

In [113]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [115]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [116]:
#reshape

In [117]:
np.arange(10).reshape(2, 5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [118]:
np.arange(10).reshape(5, 2)


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [119]:
# linspace

In [120]:
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [121]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [122]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [123]:
# zeros, ones, empty

In [124]:

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [125]:
np.zeros((3, 3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [126]:
np.zeros((3, 3), dtype=np.int)


C:\Users\Pegah\AppData\Local\Temp/ipykernel_10980/2110505395.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.zeros((3, 3), dtype=np.int)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [127]:
np.ones(5)


array([1., 1., 1., 1., 1.])

In [128]:
np.ones((3, 3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [129]:
np.empty(5)


array([1., 1., 1., 1., 1.])

In [130]:
np.empty((2, 2))


array([[0.25, 0.5 ],
       [0.75, 1.  ]])

In [131]:
# identity and eye¶


In [132]:
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [133]:
np.eye(3, 3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [134]:
np.eye(8, 4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [137]:
"Hello World"[6]

'W'